events {}

http {

  upstream ai_router {
    server ai-router:4000;
  }

  upstream n8n_service {
    server n8n:5678;
  }

  upstream cal_service {
    server calcom:3000;
  }

  # ================================
  # HTTP → HTTPS Redirect
  # ================================
  server {
    listen 80;
    server_name api.codeco.tech;

    location / {
      return 301 https://$host$request_uri;
    }
  }

  # ================================
  # API
  # ================================
  server {
    listen 443 ssl;
    server_name api.codeco.tech;

    ssl_certificate /opt/codeco/certs/fullchain.pem;
    ssl_certificate_key /opt/codeco/certs/privkey.pem;

    location = /health {
       default_type application/json;
       return 200 '{"status":"ok"}';
    }

    location / {
      proxy_pass http://ai_router;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }

    location /paymentsuccess {
      proxy_pass http://ai_router/paymentsuccess;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }

  # ================================
  # n8n
  # ================================
  server {
    listen 80;
    server_name n8n.codeco.tech;

    location / {
      proxy_pass http://n8n_service;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }

  # ================================
  # Cal.com
  # ================================
  server {
    listen 80;
    server_name cal.codeco.tech;

    location / {
      proxy_pass http://cal_service;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }

}
